POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9saXZlcjEyMyIsImlkIjoiNjg1MTQ2ZDJhYmRjZmJhYWNhZTQ3ZDQ1IiwiaWF0IjoxNzUwMjMwNzYyfQ.pJppET55o63DaiW_mB_w9EVz-7RYFVUnaCstsoQxmRk

{
  "title": "Lumikko ja yhdeksän muuta",
  "author": "Pasi Jääskeläinen",
  "url": "verycoolwebsite.com",
  "likes": 500,
  "userId": "685146d2abdcfbaacae47d45"
}